const data = { 
  places: [
    {
      id: 1,
      name: "Atlas Pizza",
      address1: "6529 SE Foster Rd",
      address2: "",
      city: "Portland",
      state: "OR",
      zipcode: "97206",
      coordinates: {
        lat: 45.489200,
        lng: -122.595070
      },
      neighborhood: "SE",
      phone: "503-232-3004",
      website: "http://atlaspizzapdx.com",
      hours: [
        {
          "dayOfWeek": "Monday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "12:00 pm",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "12:00 pm",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "12:00 pm",
          "closes": "11:00 pm",
        },
      ],
      date_added: "2019-06-13",
      category: ["restaurants",],
      descriptors: [ "pizza", "arcade", "beer" ],
      features: { 
        "toys": true, 
        "play area": true, 
        "arcade": true,
        "quick service": true,
        "all ages": true,
        "comfortable seating": true,
        "friendly staff": true,
        "kids menu": false,
        "highchairs/boosters": false,
        "changing station": false,
        "flexible": true,
        "patio/sidewalk": true,
      },
      images: [
        {
          id: 1,
          src: 'https://lh3.googleusercontent.com/ir83SjI1lJpHK4E5vQFwD7LfyE__eKaIvBtmFf1nV5wyfq-z5LVe4u7PuQvQ7ycqsFlGMe5vw3UNRB86G3SjLckIZKHgFSkz0-oQdLAAP2UxlUwq-HqDA116RjcI3iG-lA1ftsYr9S4=w2400',
          title: `Atlas Pizza's 'Jalapeno Popper' pie`,
          place_id: 1,
          user_id: 2,
          review_id: 1,
        },
        {
          id: 2,
          src: 'https://lh3.googleusercontent.com/CjUvS4WgCiSRTsUUAryiPcczqAdyaSDhDg1ZTT6OrdgjfdNiTE5Q14pwI-C2m49tSjQHMnBxDgpiZyYZkxEDE3KzI3DWLsT631ROrF1zTuJcBqEXcRN8PP5U3EcG-bmMclE_uKmWh2E=w2400',
          title: 'A rainbow over Foster Blvd',
          place_id: 1,
          user_id: 1,
          review_id: 2,
        },
      ],
      number_of_reviews: 2,
      average_review_rating: 4.5,
    },
    {
      id: 2,
      name: "Grand Central Bakery",
      address1: "4412 SE Woodstock Blvd",
      address2: "",
      city: "Portland",
      state: "OR",
      zipcode: "97206",
      coordinates: {
        lat: 45.479040,
        lng: -122.616120
      },
      neighborhood: "SE",
      phone: "503-953-1250",
      website: "https://www.grandcentralbakery.com/find-us/portland/woodstock/",
      hours: [
        {
          "dayOfWeek": "Monday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "7:00 am",
          "closes": "6:00 pm",
        },
      ],
      date_added: "2019-06-13",
      category: ["restaurants",],
      descriptors: [ "cafe", "bakery", "pastries", ],
      features: { 
        "toys": false, 
        "play area": false, 
        "arcade": false,
        "quick service": true,
        "all ages": true,
        "comfortable seating": true,
        "friendly staff": true,
        "kids menu": false,
        "highchairs/boosters": true,
        "changing station": true,
        "flexible": true,
        "patio/sidewalk": true,
      },
      images: [
        {
          id: 1,
          src: 'https://lh3.googleusercontent.com/2-dLhEkgnU4-n62Nq4X1X2u5FjGRp5Hb5Wkwq1m1cuHbAqdJmrhih2MKdggGIncaWTMf3STdOGZgOMwaYa3nx1k6j2dA6Fs6kyys-i1yW2kw1jxG-Q9EmijXM0EosofSIpsTyoAdJns=w2400',
          title: 'Fresh loaf!',
          place_id: 2,
          user_id: 3,
          review_id: 3,
        },
        {
          id: 2,
          src: 'https://lh3.googleusercontent.com/HDU-n0GE-3Glgn8o1WEDaRsUzhuA5qvLqoZjZzQCx1LwtOucN9zmWZ3YX_Lnce4_kp-sBcB8-6wXjiq9NjacD27tysnJt6eITsmlWGHj1WIRiCpLIzme95n-vK3ydgNBizXtHXTrkMY=w2400',
          title: 'A box of assorted pastries',
          place_id: 2,
          user_id: 3,
          review_id: 3,
        },
      ],
      number_of_reviews: 1,
      average_review_rating: 4,
    },
    {
      id: 3,
      name: "Hopworks Urban Brewery: Powell",
      address1: "2944 SE Powell Blvd",
      address2: "",
      city: "Portland",
      state: "OR",
      zipcode: "97206",
      coordinates: {
        lat: 45.497010,
        lng: -122.635210
      },
      neighborhood: "SE",
      phone: "503-232-4677",
      website: "https://hopworksbeer.com/eat/powell/",
      hours: [
        {
          "dayOfWeek": "Monday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "11:00 am",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "11:00 am",
          "closes": "12:00 am",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "11:00 am",
          "closes": "11:00 pm",
        },
      ],
      date_added: "2019-06-13",
      category: ["restaurants",],
      descriptors: [ "pizza", "burgers", "beer",],
      features: { 
        "toys": true, 
        "play area": true, 
        "arcade": false,
        "quick service": true,
        "all ages": true,
        "comfortable seating": true,
        "friendly staff": true,
        "kids menu": true,
        "highchairs/boosters": true,
        "changing station": true,
        "flexible": true,
        "patio/sidewalk": true,
      },
      images: [
        {
          id: 1,
          src: 'https://lh3.googleusercontent.com/7dA-7cI0-Ta-7QQ3k4ttgNuKjFNBhizMLXGF873v5nOWioblzEvWQn5r9HrZ4U13C31lZARcw3Yh6ZqiPX0hfqtRE9tpy3h9-toE9vf2QHDGd-355aLAWV5mOprQTJ0CybWQwO3zj-Y=w2400',
          title: 'Beer sampler',
          place_id: 3,
          user_id: 4,
          review_id: 4,
        },
        {
          id: 2,
          src: 'https://lh3.googleusercontent.com/QsdaLX-XqlpIMZO2I1rv_pBubbRyxB2PHg4c2B-Pg2nSU0gV1Cgkbq759pKLU-ZleVam7r_Kh7DOiFjiCUlc6fzPFADGTgtlV73QeFk_0JUM_PAyaHFtn7b81p0QhjQIJjMfiaiKHNc=w2400',
          title: "HUB exterior",
          place_id: 3,
          user_id: 4,
          review_id: 4
        }
      ],
      number_of_reviews: 1,
      average_review_rating: "4.4",
    },
    {
      id: 4,
      name: "Hammer and Jacks",
      address1: "6416 SE Foster Rd",
      address2: "",
      city: "Portland",
      state: "OR",
      zipcode: "97206",
      coordinates: {
        lat: 45.497560,
        lng: -122.611350
      },
      neighborhood: "SE",
      phone: "503-894-9150",
      website: "https://www.hammerandjacks.com/",
      hours: [
        {
          "dayOfWeek": "Monday",
          "opens": "10:00 am",
          "closes": "05:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "10:00 am",
          "closes": "05:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "10:00 am",
          "closes": "05:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "10:00 am",
          "closes": "05:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "10:00 am",
          "closes": "06:00 pm",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "10:00 am",
          "closes": "06:00 pm",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "10:00 am",
          "closes": "05:00 pm",
        },
      ],
      date_added: "2019-07-06",
      category: [ "toy stores", "indoor play" ],
      descriptors: [ "toy store", "indoor play", "community space" ],
      features: { 
        "toys": true, 
        "play area": true, 
        "arcade": false,
        "quick service": false,
        "all ages": false,
        "comfortable seating": true,
        "friendly staff": true,
        "kids menu": false,
        "highchairs/boosters": false,
        "changing station": true,
        "flexible": true,
        "patio/sidewalk": false,
      },
      images: [
        {
          id: 1,
          src: 'https://lh3.googleusercontent.com/t2wKP7xtx15nC8iSL6XGdR1oC5uYo6K8wxSFoC3LBBkVXlc7941TktpLLWV5VGmx_xFH0tCd-50qASnbtPXNtCo-xphQ16G33oZKeXLc-pRCe8wc5bnbpt-HqMqTsO3-7OmEI5t27EM=w2400',
          title: `Hammer and Jacks storefront`,
          place_id: 4,
          user_id: 1,
        },
        {
          id: 2,
          src: 'https://lh3.googleusercontent.com/gfamj0g-ieATA5fUX3ocTGlHAdKb-Bqrq-xm76mztNuWkijxGqREhE4htmH39rtUslLznfmLORL4ZMmN8tbKOd45z3izdHEfqHfX7MCKg86AWxFFba9XnmLYJIlaG-6oF0USXNrktEs=w2400',
          title: 'Unicorn party balloon!',
          place_id: 4,
          user_id: 1,
        },
        {
          id: 3,
          src: 'https://lh3.googleusercontent.com/mUsYElLLTLWoxwp5ydk9H-Z6prAG-92_NCzh3CS9xdbDqyr8RkOxnulQLmLUs-lZPtdzF3Vs9MB86qCvQXL_wPdkla3l15NkAlkHGYAbVx9yVKz-iuMh32n6pnK2iMSAxtvtvSXXoYk=w2400',
          title: 'Castle fort slide and indoor play area',
          place_id: 4,
          user_id: 1,
        },
      ],
      number_of_reviews: 1,
      average_review_rating: 5,
    },
    {
      id: 5,
      name: "Crystal Springs Rhododendron Garden",
      address1: "5801 SE 28th Ave",
      address2: "",
      city: "Portland",
      state: "OR",
      zipcode: "97202",
      coordinates: {
        lat: 45.480400,
        lng: -122.635399
      },
      neighborhood: "SE",
      phone: "503-771-8386",
      website: "https://www.portlandoregon.gov/parks/finder/index.cfm?action=ViewPark&PropertyID=27",
      hours: [
        {
          "dayOfWeek": "Monday",
          "opens": "06:00 am",
          "closes": "10:00 pm",
        },
        {
          "dayOfWeek": "Tuesday",
          "opens": "06:00 am",
          "closes": "10:00 pm",
        },
        {
          "dayOfWeek": "Wednesday",
          "opens": "06:00 am",
          "closes": "10:00 pm",
        },
        {
          "dayOfWeek": "Thursday",
          "opens": "06:00 am",
          "closes": "10:00 pm",
        },
        {
          "dayOfWeek": "Friday",
          "opens": "06:00 am",
          "closes": "10:00 pm",
        },
        {
          "dayOfWeek": "Saturday",
          "opens": "06:00 am",
          "closes": "10:00 pm",
        },
        {
          "dayOfWeek": "Sunday",
          "opens": "06:00 am",
          "closes": "10:00 pm",
        },
      ],
      date_added: "2019-07-10",
      category: [ "gardens", "attractions", "parks", ],
      descriptors: [ "garden", "park", "wildlife" ],
      features: { 
        "toys": false, 
        "play area": false, 
        "arcade": false,
        "quick service": false,
        "all ages": false,
        "comfortable seating": false,
        "friendly staff": true,
        "kids menu": false,
        "highchairs/boosters": false,
        "changing station": true,
        "flexible": true,
        "patio/sidewalk": true,
        "wildlife/nature": true,
        "stroller accessible": true,
        "rainy day fun": true,
      },
      images: [
        {
          id: 1,
          src: 'https://lh3.googleusercontent.com/CSSSQJ8V9mZ6jQwNCC1PMSaCimRjCjwxsKpyihqe5j57OWtVPkR3SNneSRiGZSbQy62Z1haz-p638MLFraVE_lgcZdsIeW4x_-r_JSziuRfof7-ztkteQ6cZvju0lvsYW8bvACKcfis=w2400',
          title: `Pink rhododendrons in bloom`,
          place_id: 5,
          user_id: 1,
        },
        {
          id: 2,
          src: 'https://lh3.googleusercontent.com/-bXD01_TzgdWhrKltvgPjK6a4YhpWY2jawymfmd4gKVcu869c4kJs-s2tlp5n_40rEDCYopM99TBDggJ0CVFI7Okx8b6TDtPsSswqY2S4v2DnMRq4e8SRYXcSyDnP8KNt3YY6zQvqb0=w2400',
          title: 'Ducks overlooking the garden',
          place_id: 5,
          user_id: 1,
        },
        {
          id: 3,
          src: 'https://lh3.googleusercontent.com/tn6yQ6erdO7uwlXXn3v7jXkDz6avzH84V1BUzZb1yEnDTIUWF-vnDkqEFWTBu-xxicSP3XLWPYPfs5Z7f-AKys4Lr0i8NcC8G7dgf3UH0RjlHr8axiGMbVs-LDbmuPokPZzyYLKSRpc=w2400',
          title: 'Garden path by the pond',
          place_id: 5,
          user_id: 1,
        },
      ],
      number_of_reviews: 1,
      average_review_rating: 5,
    },
  ],
  users: [
    { 
      id: 1,
      full_name: "Charlie Kelly",
      email: "charlie@alwayssunny.com",
      password: "Charlie100%",
      display_name: "Charlie",
      date_created: "2019-06-13",
    },
    { 
      id: 2,
      full_name: "Ronald McDonald",
      email: "mac@alwayssunny.com",
      password: "Mac100%!",
      display_name: "Mac",
      date_created: "2019-06-13",
    },
    { 
      id: 3,
      full_name: "Deandra Reynolds",
      email: "sweetdee@alwayssunny.com",
      password: "SweetDee100%",
      display_name: "Sweet Dee",
      date_created: "2019-06-13",
    },
    { 
      id: 4,
      full_name: "Dennis Reynolds",
      email: "dennis@alwayssunny.com",
      password: "Dennis100%",
      display_name: "Dennis",
      date_created: "2019-06-13",
    },
    {
      id: 5,
      full_name: "Leah White",
      email: "leahawhite@gmail.com",
      password: "lool00",
      display_name: "Leah",
      date_created: "2019-07-06",
    }
  ],
  reviews: [
  { 
    id: 1,
    star_rating: 5,
    text: "Atlas is our new favorite spot for a quick, painless dinner with our toddler. It's super casual -- order slices or pies at the counter, and they call your name for pickup when it's ready. Since it's new, the play area is pretty clean and well-stocked. There's an old church pew there for parents to sit and supervise, but the open floor plan means that you can see the play area from pretty much every table. We've only ordered slices, so we've never had to wait long. We're usually in and out in 30 minutes, which is just about perfect for us.",
    date_created: "2019-06-13",
    place_id: 1,
    user_id: 5,
    images: [
      {
        id: 1,
        src: 'https://lh3.googleusercontent.com/QDwk6G6ZCwYzVH-yJHQ824GZ1wKW2XXus8hxxdH-4AAHz-FejC-UVydyE5le1ZvPTIo1cXw1G25qhljwS8dgyIedCCFtIxBonznVQ4LfaPDEZVWmqKS1vFqVUFFNmMmMlKQ5eCpfhNI=w2400',
        title: `Atlas Pizza's play area`,
        place_id: 1,
        user_id: 5,
      },
      {
        id: 2,
        src: 'https://lh3.googleusercontent.com/onV_ZZwQ1hbj_rqeAPM_B09jkj3Zc597V9BP2G2_43fexr570YJSrjhH2dkQJ8PEchSDgk8MPXcT_HC6R8-FJC2D4LHi9nuHYE6elMzmIbqm-tFsCL_qQSRsWBfdh0ZfDCQCIk560g8=w2400',
        title: `Hi, greasy handprint. (Sorry, Atlas.)`,
        place_id: 1,
        user_id: 5,
      },
    ]
  },
  { 
    id: 2,
    star_rating: 4,
    text: "Very easy place to take kids of all ages. Nice toy area with a great variety of toys!",
    date_created: "2019-06-13",
    place_id: 1,
    user_id: 1,
    images: [],
  },
  { 
    id: 3,
    star_rating: 4,
    text: "There's no play area or toys at this GCB location, but the sidewalk picnic tables are a bonus.",
    date_created: "2019-06-13",
    place_id: 2,
    user_id: 5,
    images: [ 
      {
        id: 1,
        src: 'https://lh3.googleusercontent.com/EsXFx4tHCGD6rT29rS7BLHwkqIDlr5Zp83oY6NGaQT36lbLdjmToppVmFXCntWRnEknaeEkPkMtiGgBihgGkDZBzcvPhVQUwwhHPdrXQGYKP4mIpktYDDg70WPewBPrj6rKrUYkw3YA=w2400',
        title: 'GCB cookies are the best!',
        place_id: 2,
        user_id: 5,
        review_id: 3,
      },
    ],
  },
  { 
    id: 4,
    star_rating: 4,
    text: "HUB is pretty well known for being one of the kid-friendliest pubs in Portland, and they deliver. The food and beer are pretty good (including a kids' menu), but we come for the play areas. There are two large separate play areas, one on each floor. One has a chalkboard, the other a train table, and many toys and books strewn between each. HUB also supplies coloring sheets and crayons. The wait can be long during peak hours, so we avoid weekends or try to go as close to 5:00 p.m. as possible.",
    date_created: "2019-07-06",
    place_id: 3,
    user_id: 5,
    images: [
      {
        id: 1,
        src: 'https://lh3.googleusercontent.com/4jdEc5VGXsWFLqqeulTdHEnFXMISxcNJMikB-iUZvuU-_N9OaNFPwmsJi2xxptyIuN6GOFW5obNOyzEdbZ8GR0GPZOg14WSeqgJYtazOz1JYGLry6qdtW4ksCSwNNN_N-uPw0Zpy8xg=w2400',
        title: 'BRIO train set upstairs',
        place_id: 3,
        user_id: 5,
      },
      {
        id: 2,
        src: 'https://lh3.googleusercontent.com/rTxUKWUh6FB0irUEViYVD28t-7o1iaEhiO4saV5T6HJHMcyKV-sBkKiBif7r0Rmj3W48OcmU2OY4zEPnB3lXDJ6q-qyWuqTfO0PWpn5V_bVkE23sdfmC_cOYEkyJFFhkIDq7EKxtQx8=w2400',
        title: "Crayons and coloring sheets while you wait",
        place_id: 3,
        user_id: 5,
      },
    ],
  },
  { 
    id: 5,
    star_rating: 5,
    text: "Hammer and Jacks is a wonderful toy store, play room, and community space. The price to use the play space ($5 or less with the punch card) is very reasonable, and the owner frequently switches up the toys so regulars don't get too bored. We don't come as often as we used to when he was a younger, wobblier toddler, but he still enjoys it when we do. The main feature of the room is a cleverly designed wooden castle structure with peekaboo windows, a runway of sorts that leads to a slide, and a carpeted tunnel underneath. There's also a dressup chest and a stage of sorts for performing, plenty of vehicles, a play kitchen, a Magna-Tiles light table, and more. The big items in the toy store are a bit pricy for us (lots of European, indie and wooden toys), but we've picked up plenty of smaller items for under $20. The selection is always interesting and unique, and the owner is very warm and inviting.",
    date_created: "2019-07-08",
    place_id: 4,
    user_id: 5,
    images: [],
  },
  { 
    id: 6,
    star_rating: 5,
    text: "The rhodie garden is a park we can visit at any time of the year. It's of course most beautiful in the spring with all of the flowers blooming, but it's also fun to watch the ducks and splash in puddles on cold, rainy days. You can buy duck/geese food at the gate for $1/bag, though the birds are active enough without any encouragement. The paths are always well groomed and easy to walk on, even on the wettest days. With the water features, flowers, bridges, and wildlife, there's plenty to see and do here.",
    date_created: "2019-07-10",
    place_id: 5,
    user_id: 5,
    images: [
      {
        id: 1,
        src: 'https://lh3.googleusercontent.com/_QvxNBcamd3hHO7STXX_GOzoOlLnzl8FEwwWc2SQN4pjmVp4sBa-T1w86MWYTqXa8bcsO81itLMmDHtG_yZXS_Q06PTszZm3l4tISvj291hsuqHimqiJULOH1ZX9BdYaHGV6u76fMQI=w2400',
        title: 'Hustling across the bridge',
        place_id: 5,
        user_id: 5,
      },
      {
        id: 2,
        src: 'https://lh3.googleusercontent.com/YagxcpA2XaaXHSdRnBrxfTEmhTTANSnc-o3qoP6nMDaJUv-wdFRjh2rbxxmbj7IvsKby_L64j2A_iyz2BLJUXEdtIOlb-AX9Srk5SHYJWb6H6gZmATzgxWYAkbABS9vIw2dArhokPNU=w2400',
        title: "Water's edge",
        place_id: 5,
        user_id: 5,
      },
      {
        id: 3,
        src: 'https://lh3.googleusercontent.com/Y65KCP7rJQdp40AeXyGfKyKuVtjc4uK2LoVNQ2z9ok6IA7u8uKWzjPJOWCwEpBPsQtoD26k3tLgwP3uPx0PY4Mvk__yFh3QG_AXkruSKqnu2K7Yj3Qb2U6QgxV9jhH4VuTz7ZsOAhXM=w2400',
        title: "Cherry blossom 'snow'",
        place_id: 5,
        user_id: 5,
      },
    ],
  },
  ]
};

export default data;