CREATE TABLE places (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  name TEXT NOT NULL,
  address TEXT NOT NULL,
  city TEXT NOT NULL, 
  state TEXT NOT NULL,
  zipcode TEXT NOT NULL, 
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL, 
  neighborhood text NOT NULL, 
  phone VARCHAR(30) NOT NULL, 
  website TEXT NOT NULL,
  date_added TIMESTAMP DEFAULT now() NOT NULL,
  category text [] not null,
  descriptors text [] not null,
  features text [] not null
);

CREATE TABLE place_hours (
  id INTEGER primary key generated by default as identity,
  day_id INTEGER NOT NULL, 
  opens TEXT NOT NULL, 
  closes TEXT NOT NULL,
  place_id INTEGER REFERENCES places(id) NOT NULL 
);
