CREATE TYPE neighborhood AS ENUM (
  'N',
  'NE',
  'NW',
  'Downtown',
  'SW',
  'SE',
  'Beaverton',
  'Vancouver',
  'Clackamas',
  'Milwaukie'
);

CREATE TABLE places (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  name TEXT NOT NULL,
  address1 TEXT NOT NULL,
  address2 TEXT,
  city TEXT NOT NULL, 
  state TEXT NOT NULL,
  zipcode TEXT NOT NULL, 
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL, 
  neighborhood NEIGHBORHOOD NOT NULL, 
  phone VARCHAR(30) NOT NULL, 
  website TEXT NOT NULL,
  date_added DATE DEFAULT CURRENT_DATE NOT NULL
);

CREATE TABLE place_hours (
  id INTEGER primary key generated by default as identity,
  dayOfWeek TEXT NOT NULL, 
  opens TEXT NOT NULL, 
  closes TEXT NOT NULL,
  place_id INTEGER REFERENCES places(id) NOT NULL 
);

CREATE TABLE descriptors (
  id INTEGER primary key generated by default as identity,
  descriptor TEXT NOT NULL
);

CREATE TABLE place_descriptors (
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL,
  descriptor_id INTEGER REFERENCES descriptors(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (place_id, descriptor_id)
);

CREATE TABLE category (
  id INTEGER primary key generated by default as identity,
  category_name TEXT NOT NULL
);

CREATE TABLE place_category (
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL,
  category_id INTEGER REFERENCES category(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (place_id, category_id)
);

CREATE TABLE features (
  id INTEGER primary key generated by default as identity,
  feature TEXT NOT NULL
);

CREATE TABLE place_features (
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL,
  feature_id INTEGER REFERENCES features(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (place_id, feature_id)
);

CREATE TABLE place_images (
  id INTEGER primary key generated by default as identity,
  src TEXT NOT NULL,
  title TEXT NOT NULL,
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL
);