CREATE TYPE neighborhood AS ENUM (
  'N',
  'NE',
  'NW',
  'Downtown',
  'SW',
  'SE',
  'Beaverton',
  'Vancouver',
  'Clackamas',
  'Milwaukie'
);

create type category as enum (
	'restaurant',
	'attraction',
	'museum',
	'park',
	'indoor play',
	'toy store'
);

CREATE TYPE feature AS ENUM (
  'toys',
  'play area',
  'arcade',
  'quick service',
  'all ages',
  'comfortable seating',
  'friendly staff',
  'kids menu',
  'highchairs/boosters',
  'changing station',
  'flexible',
  'patio/sidewalk',
  'wildlife/nature',
  'stroller accessible',
  'rainy day fun'
);

CREATE TABLE places (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  name TEXT NOT NULL,
  address1 TEXT NOT NULL,
  address2 TEXT,
  city TEXT NOT NULL, 
  state TEXT NOT NULL,
  zipcode TEXT NOT NULL, 
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL, 
  neighborhood NEIGHBORHOOD NOT NULL, 
  hours json not null,
  phone VARCHAR(30) NOT NULL, 
  website TEXT NOT NULL,
  date_added DATE DEFAULT CURRENT_DATE NOT null,
  category category [] not null,
  descriptors text [] not null,
  features feature [] not null,
  images json not null
);