CREATE TABLE place_hours (
  id INTEGER primary key generated by default as identity,
  day_id INTEGER NOT NULL, 
  opens TEXT NOT NULL, 
  closes TEXT NOT NULL,
  place_id INTEGER REFERENCES places(id) NOT NULL 
);
