CREATE TABLE images (
  id INTEGER NOT NULL,
  src TEXT NOT NULL,
  title TEXT,
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL
);