CREATE TABLE images (
  id TEXT NOT NULL PRIMARY KEY,
  src TEXT NOT NULL,
  title TEXT,
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL,
  user_id INTEGER REFERENCES users(id) ON DELETE CASCADE NOT NULL,
  date_created TIMESTAMP DEFAULT now() NOT NULL
);