CREATE TABLE places (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  name TEXT NOT NULL,
  address1 TEXT NOT NULL,
  address2 TEXT,
  city TEXT NOT NULL, 
  state TEXT NOT NULL,
  zipcode TEXT NOT NULL, 
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL, 
  neighborhood TEXT NOT NULL, 
  phone VARCHAR(30) NOT NULL, 
  website TEXT NOT NULL,
  date_created DATE DEFAULT now() NOT NULL
);