CREATE TABLE category (
  id INTEGER primary key generated by default as identity,
  category_name TEXT NOT NULL
);

CREATE TABLE place_category (
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL,
  category_id INTEGER REFERENCES category(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (place_id, category_id)
);

INSERT INTO category
  (category_name)
VALUES  
  ('restaurant'),
  ('toy store'),
  ('indoor play'),
  ('park'),
  ('attraction'),
  ('museum');

INSERT INTO place_category
  (place_id, category_id)
VALUES
  (1, 1),
  (2, 1),
  (3, 1),
  (4, 2),
  (4, 3),
  (5, 4),
  (5, 5);