CREATE TABLE descriptors (
  id INTEGER primary key generated by default as identity,
  descriptor TEXT NOT NULL
)

CREATE TABLE place_descriptors (
  place_id INTEGER REFERENCES places(id) ON DELETE CASCADE NOT NULL,
  descriptor_id INTEGER REFERENCES descriptors(id) ON DELETE CASCADE NOT NULL,
  PRIMARY KEY (place_id, descriptor_id)
)

INSERT INTO descriptors
  (descriptor)
VALUES  
  ('pizza'),
  ('arcade'),
  ('beer'),
  ('cafe'),
  ('bakery'),
  ('sandwiches'),
  ('burgers'),
  ('toy store'),
  ('community space'),
  ('garden'),
  ('park'),
  ('wildlife')

INSERT INTO place_descriptors
  (place_id, descriptor_id)
VALUES
  (1, 1),
  (1, 2),
  (1, 3),
  (2, 4),
  (2, 5),
  (2, 6),
  (3, 1),
  (3, 3),
  (3, 7);