BEGIN;

TRUNCATE reviews RESTART IDENTITY CASCADE;

INSERT INTO reviews
  (rating, text, date_created, place_id, user_id)
VALUES
  (5, 'Atlas is our new favorite spot for a quick, painless dinner with our toddler. It''s super casual -- order slices or pies at the counter, and they call your name for pickup when it''s ready. Since it''s new, the play area is pretty clean and well-stocked. There''s an old church pew there for parents to sit and supervise, but the open floor plan means that you can see the play area from pretty much every table. We''ve only ordered slices, so we''ve never had to wait long. We''re usually in and out in 30 minutes, which is just about perfect for us.', '2019-06-13', 1, 1),
  (4, 'Very easy place to take kids of all ages. Nice toy area with a great variety of toys!', '2019-06-13', 1, 2),
  (4, 'There''s no play area with toys at this GCB location, but the sidewalk picnic tables are a bonus.', '2019-06-13', 2, 1),
  (4, 'HUB is pretty well known for being one of the kid-friendliest pubs in Portland, and they deliver. The food and beer are pretty good (including a kids'' menu), but we come for the play areas. There are two large separate play areas, one on each floor. One has a chalkboard, the other a train table, and many toys and books strewn between each. HUB also supplies coloring sheets and crayons. The wait can be long during peak hours, so we avoid weekends and try to go as close to 5:00 p.m. as possible.', '2019-07-06', 3, 1),
  (5, 'Hammer and Jacks is a wonderful toy store, play room, and community space. The price to use the play space ($5 or less with the punch card) is very reasonable, and the owner frequently switches up the toys so regulars don''t get too bored. We don''t come as often as we used to when he was a younger, wobblier toddler, but he still enjoys it when we do. The main feature of the room is a cleverly designed wooden castle structure with peekaboo windows, a runway of sorts that leads to a slide, and a carpeted tunnel underneath. There''s also a dressup chest and a stage of sorts for performing, plenty of vehicles, a play kitchen, a Magna-Tiles light table, and more. The big items in the toy store are a bit pricy for us (lots of European, indie and wooden toys), but we''ve picked up plenty of smaller items for under $20. The selection is always interesting and unique, and the owner is very warm and inviting.', '2019-07-08', 4, 1),
  (5, 'The rhodie garden is a park we can visit at any time of the year. It''s of course most beautiful in the spring with all of the flowers blooming, but it''s also fun to watch the ducks and splash in puddles on cold, rainy days. You can buy duck/geese food at the gate for $1/bag, though the birds are active enough without any encouragement. The paths are always well groomed and easy to walk on, even on the wettest days. With the water features, flowers, bridges, and wildlife, there''s plenty to see and do here.', '2019-07-10', 5, 1);

COMMIT;