DROP TYPE IF EXISTS category;
CREATE TYPE category AS ENUM (
  'all',
  'attraction',
  'community center'
  'indoor play'
  'museum',
  'park',
  'restaurant',
  'toy store',
)

DROP TYPE IF EXISTS neighborhood;
CREATE TYPE neighborhood AS ENUM (
  'All Portland',
  'N',
  'NE'
  'NW'
  'Downtown',
  'SW',
  'SE',
  'Beaverton',
  'Vancouver',
  'Clackamas',
  'Milwaukie',
)

drop table if exists places;
CREATE TABLE places (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY, 
  name TEXT NOT NULL,
  address1 TEXT NOT NULL,
  address2 TEXT,
  city TEXT NOT NULL, 
  state TEXT NOT NULL,
  zipcode TEXT NOT NULL, 
  latitude FLOAT NOT NULL,
  longitude FLOAT NOT NULL, 
  neighborhood1 NEIGHBORHOOD DEFAULT 'All Portland' NOT NULL, 
  neighborhood2 NEIGHBORHOOD NOT NULL, 
  phone VARCHAR(30) NOT NULL, 
  website TEXT NOT NULL,
  category1 CATEGORY DEFAULT 'all' NOT NULL,
  category2 CATEGORY NOT NULL,
  category3 CATEGORY,
  date_added TIMESTAMP DEFAULT now() NOT NULL, 
  number_of_reviews INTEGER NOT NULL, 
  average_review_rating REAL NOT NULL,
);

drop table if exists place hours;
CREATE TABLE place hours (
  id INTEGER primary key generated by default as identity,
  dayOfWeek TEXT NOT NULL, 
  opens TEXT NOT NULL, 
  closes TEXT NOT NULL,
  place_id INTEGER NOT NULL, 
);

drop table if exists descriptors;
CREATE TABLE descriptors (
  id INTEGER primary key generated by default as identity,
  title TEXT NOT NULL,
  place_id INTEGER NOT NULL,
)

drop table if exists features;
CREATE TABLE features (
  id INTEGER primary key generated by default as identity,
  name TEXT NOT NULL,
  place_id INTEGER NOT NULL,
);

drop table if exists place_images;
CREATE TABLE place_images (
  id INTEGER primary key generated by default as identity,
  src TEXT NOT NULL,
  title TEXT NOT NULL,
  place_id INTEGER NOT NULL,
)