drop table if exists reviews;
CREATE TABLE reviews (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  star_rating INTEGER NOT NULL,
  text TEXT,
  date_created TIMESTAMP DEFAULT now() NOT NULL,
  place_id INTEGER NOT NULL,
  user_id INTEGER NOT NULL,
)

drop table if exists review_images;
CREATE TABLE review_images (
  id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
  src TEXT NOT NULL,
  TITLE TEXT NOT NULL,
  review_id INTEGER NOT NULL,
)